### ISSUE TITLE
Examples of modules

### ISSUE THREAD

**Issue by jonchay** [backbone-boilerplate/backbone-boilerplate#257]
Hi, I'm new to backbone and I'm giving this boilerplate a shot and I love it so far. Do you have any examples on how javascript files in <code>app/modules</code> folder gets included? It's not automatically compiled with the <code>app/*.js</code> files during the requirejs task.

**Comment by tbranyen** [comment]
It uses AMD, check out RequireJS or Google around for information on how to require and build these modules.

An example application that has modules included and built: https://github.com/tbranyen/github-viewer
