### ISSUE TITLE
Running Karma: ReferenceError: Can't find variable: waitsFor

### ISSUE THREAD

**Issue by mromanoff** [backbone-boilerplate/backbone-boilerplate#260]
I'm getting error. Running Karma with Jasmine.

Running "karma:run" (karma) task
......
PhantomJS 1.9.7 (Mac OS X) async multiple async FAILED
	ReferenceError: Can't find variable: waitsFor
	    at /Users/mromanoff/Sites/equifit/public/apps/equifit/test/jasmine/specs/example.spec.js:74
	    at /Users/mromanoff/Sites/equifit/public/apps/equifit/node_modules/karma-jasmine/lib/boot.js:117
	   ..............

**Comment by tbranyen** [comment]
Should be fixed here: https://github.com/backbone-boilerplate/backbone-boilerplate/commit/e643af35b43d07d1cf26eafbbd9768209a131eb7
